# Generated by Django 3.2.2 on 2021-06-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('document_up', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='file_upload',
        ),
    ]
